### ISSUE TITLE
InterfaceImpl table returns wrong Class

### ISSUE THREAD

**Issue by jagobagascon** [tdakkota/win32metadata#33]
Hi!

I'm trying to use this library to read `winmd` files and generate some Golang code, but the values I'm seeing in the `InterfaceImpl` table do not match the ones in the IDL or the `winmd` file.

I'm parsing the `C:\Windows\System32\WinMetadata\Windows.Storage.winmd` file, and listing all the values in `InterfaceImpl`. [According to the IDL](https://github.com/tpn/winsdk-10/blob/9b69fd26ac0c7d0b83d378dba01080e93349c2ed/Include/10.0.14393.0/winrt/windows.storage.streams.idl#L450), the `Buffer` class implements `IBuffer`. But `Buffer` does not appear anywhere in the table, instead I'm getting this:
```
Windows.Storage.Streams.ByteOrder implements Windows.Storage.Streams.IBuffer
```

If I open the `winmd` file with the IL Disassembler, this is what I see:

![Screenshot 2022-06-09 at 18 01 00](https://user-images.githubusercontent.com/12712433/172892740-efa2a219-0dfd-4e16-aedc-3b908597fdae.png)

Notice how both classes are side by side (I'm guessing there must be an index issue somewhere).

**I checked all results from the `InterfaceImpl` table, and all the classes are shifted by one**. `IBuffer` is implementing what `FileRandomAccessStream` should. `FileRandomAccessStream` implements what `FileOutputStream` should, and so on:

```
Windows.Storage.Streams.IBuffer implements Windows.Storage.Streams.IRandomAccessStream
Windows.Storage.Streams.IBuffer implements Windows.Storage.Streams.IOutputStream
Windows.Storage.Streams.IBuffer implements Windows.Foundation.IClosable
Windows.Storage.Streams.IBuffer implements Windows.Storage.Streams.IInputStream
```

![Screenshot 2022-06-09 at 18 06 09](https://user-images.githubusercontent.com/12712433/172893580-a0287ea4-452b-4287-a2b6-94c41cadb934.png)

I tried to debug the code and come up with a solution myself, but I'm not familiar with the format of the Windows Metadata files.

**Comment by tdakkota** [comment]
It seems to be off-by-one error.

I've created [v0.1.0-pre](https://github.com/tdakkota/win32metadata/releases/tag/v0.1.0-pre) release with fix. 

Can you try it?

**Comment by jagobagascon** [comment]
Hi @tdakkota, does this mean that whenever I'm using an `Index` to read a row, I should add the `- 1` myself? Or should I exclusively rely on the `ResolveXXX` methods?

**Comment by jagobagascon** [comment]
I was asking just to be sure. I forgot to mention that calling `ResolveClass` works fine now.

Thank you for the quick response!

**Comment by tdakkota** [comment]
I close this issue as resolved.
