### ISSUE TITLE
signature reader does not return error when it fails

### ISSUE THREAD

**Issue by jagobagascon** [tdakkota/win32metadata#36]
Hi! I've found that the `SignatureReader` never fails when calling the `Method` function. It is returning `nil` when it should return the error. There are a couple of cases like this:
https://github.com/tdakkota/win32metadata/blob/8566457222bac8227c58d57026eb2e87cfb68bde/types/signature.go#L238
https://github.com/tdakkota/win32metadata/blob/8566457222bac8227c58d57026eb2e87cfb68bde/types/signature.go#L247

The method I'm reading is the `Invoke` method from the `TypedEventHandler` delegate: https://docs.microsoft.com/en-us/uwp/api/windows.foundation.typedeventhandler-2?view=winrt-22621

**Comment by tdakkota** [comment]
I've fixed it in #41. Feel free to re-open if the problem still exists.
